<a href="https://colab.research.google.com/github/mattoriq/Tugas2ML/blob/main/Tugas_2_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# melakukan import library yang diperlukan

import cv2
from google.colab.patches import cv2_imshow
import os
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras

1. Tentukan arsitektur multilayer perceptron (cukup 1 hidden layer) yang anda gunakan. Jumlah neuron di input layer = jumlah keseluruhan pixel dalam 1 image (320x240) => resize menjadi 320x240

In [ ]:
# mendeklarasikan ukuran image 320 x 240

SIZE = (320, 240)

In [ ]:
# menghubungkan code dengan google drive. membutuhkan ijin untuk akses drive.

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


2. Buatlah kode python untuk mendefinisikan arsitektur yang digunakan

In [ ]:
n_input = 320*240
n_hidden = 3
n_output = 3

3. Buatlah kode python untuk mendefinisikan fungsi Load
dataset dan visualisasi data (toriq)

In [ ]:
daisy_path = '/content/drive/My Drive/daisy_100/'
dandelion_path = '/content/drive/My Drive/dandelion_100/'
sunflower_path = '/content/drive/My Drive/sunflower_100/'

flower_data = []
flower_class = []

for file in os.listdir(daisy_path):
  if file.endswith("jpg"):
    img = getGrayScale(daisy_path + file)
    img = cv2.resize(img, SIZE, cv2.INTER_AREA)
    flower_data.append(img)
    flower_class.append(1)

for file in os.listdir(dandelion_path):
  if file.endswith("jpg"):
    img = getGrayScale(dandelion_path + file)
    img = cv2.resize(img, SIZE, cv2.INTER_AREA)
    flower_data.append(img)
    flower_class.append(2)

for file in os.listdir(sunflower_path):
  if file.endswith("jpg"):
    img = getGrayScale(sunflower_path + file)
    img = cv2.resize(img, SIZE, cv2.INTER_AREA)
    flower_data.append(img)
    flower_class.append(3)

for data in flower_data:
  plt.plot(data)
plt.show()

4. Buatlah kode python untuk mendefinisikan fungsi grayscale (boleh menggunakan library) (greyscale toriq)

In [ ]:
# membaca image secara hitam putih/gray scale. dengan adanya 0 di fungsi imread dari cv2 maka fungsi imread akan menjadi grayscale

def getGrayScale(img_path):
  return cv2.imread(img_path, 0)

5. Buatlah kode python untuk mendefinisikan fungsi aktivasi sigmoid (khoirul)


In [ ]:
# mendefinisikan fungsi aktivasi sigmoid

def sigmoid(x):
 return 1 / (1 + np.exp(-x))

6. Buatlah kode python untuk mendefinisikan fungsi algoritma pembelajaran backpropagation - Inisialisasi bobot and bias (toriq)

In [ ]:
def initialize(n_inputs, n_hidden, n_outputs):
    weight_1 = np.random.rand(n_hidden, n_inputs + 1)
    weight_2 = np.random.rand(n_outputs, n_hidden + 1)
    return weight_1, weight_2

n_inputs = 320 * 240
n_hidden = 3
n_outputs = 3

weight_1, weight_2 = initialize(n_inputs, n_hidden, n_outputs)
print(weight_1)
print(weight_2)

[[0.39964655 0.70625477 0.25998116 ... 0.44973884 0.2174186  0.18979974]
 [0.84029802 0.52156412 0.16271191 ... 0.33628132 0.76278196 0.12453369]
 [0.07284421 0.88526914 0.14263551 ... 0.41849057 0.5277384  0.08804143]]
[[0.88948607 0.21767379 0.8802659  0.44554873]
 [0.83199814 0.15620892 0.04623105 0.90900942]
 [0.43082443 0.04525503 0.06920854 0.53692395]]


7. Buatlah kode python untuk mendefinisikan fungsi algoritma pembelajaran backpropagation - menghitung error (toriq)

In [ ]:
#mendefinisikan fungsi untuk menghitung error
def countError(y, prediction):
  return y - prediction

8. Buatlah kode python untuk mendefinisikan fungsi algoritma pembelajaran backpropagation - Feedforward (toriq)


In [ ]:
#mendefinisikan fungsi feedforward
def feedForward(data):
  fp = np.dot(sig(np.dot(data, weight_1)), weight_2)
  return sig(fp)

9. Buatlah kode python untuk mendefinisikan fungsi algoritma pembelajaran backpropagation - backward (update bobot)

In [ ]:
def update_weights(weight, learning_rate, error, x):
	weight = weight + learning_rate * error * x

10. Buatlah kode python untuk mendefinisikan fungsi algoritma pembelajaran backpropagation - prediksi (Khoirul)



In [ ]:
#mendefinisikan fungsi prediksi
def predict(self, x): 
        a = np.concatenate((np.ones(1).T, np.array(x)), axis=1)      
        for l in range(0, len(self.weights)):
            a = self.sig(np.dot(a, self.weights[l]))
        return a

11. Buatlah kode python untuk mendefinisikan fungsi algoritma pembelajaran backpropagation - mendefinisikan fungsi akurasi

12. Buatlah kode python untuk mendefinisikan fungsi training (80% data) dan testing (20% data) (Khoirul)

In [ ]:
#memecah data menjadi fungsi training (80% data) dan testing (20% data)
from sklearn.model_selection import train_test_split
flower_data_train, flower_data_test, flower_class_train, flower_class_test = train_test_split(flower_data,flower_class, test_size=0.2)

#menormalisasi data
flower_data_train=np.array(flower_data_train)/255
flower_data_test=np.array(flower_data_test)/255

#mengepaskan ukuran array
from sklearn.preprocessing import LabelEncoder
flower_class_train = LabelEncoder().fit_transform(flower_class_train)
flower_class_test = LabelEncoder().fit_transform(flower_class_test)

#mengubah data menjadi format one hot
from keras.utils import to_categorical
flower_class_train = to_categorical(flower_class_train)
flower_class_test = to_categorical(flower_class_test)

In [ ]:
print(flower_class_train)

13. Visualisasikan error dan akurasi setiap epoch untuk 50 epoch, dan coba gunakan learning rate = 0,1 ; learning rate = 0,8

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras import layers
model = tf.keras.Sequential()

model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(32,32,3)))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Conv2D(64, (5, 5), activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(5,  activation='softmax'))